matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12.8.1"
cache:
  yarn: true
  directories:
    - node_modules
# install:
#   - |
#     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#       brew install yarn;
#     fi
before_deploy:
  - "pwd && ls -la"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: ./releases/*
  skip_cleanup: true
  on:
    tags: true

script:
  - "yarn install"
  - "yarn electron:build"
  - "cd dist_electron && ls -la"
  - "mkdir releases && cd ./releases && mkdir MacOS"
  - "cp ../docker-dashboard-*-mac.zip ../docker-dashboard-*.dmg ../docker-dashboard-*.dmg.blockmap ../latest-mac.yml ./MacOS"
  - "zip -r MacOS.zip ./MacOS/ && rm -R ./MacOS && cd ../ && ls -la"
