matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12.8.1"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install yarn;
    fi

script:
  - "yarn electron:build"
  - "cd dist_electron && ls -la"
